//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.30 at 12:01:35 PM IST 
//


package com.ravi.simple.ScheduledXmlGenerator.xmlmapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BOOKINGDETAILStype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BOOKINGDETAILStype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BOOKINGS" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="bookingId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="journeyDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="destination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="noOfDaysRemain" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BOOKINGDETAILStype", propOrder = {
    "bookings"
})
public class BOOKINGDETAILStype {

    @XmlElement(name = "BOOKINGS")
    protected List<BOOKINGDETAILStype.BOOKINGS> bookings;

    /**
     * Gets the value of the bookings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bookings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBOOKINGS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BOOKINGDETAILStype.BOOKINGS }
     * 
     * 
     */
    public List<BOOKINGDETAILStype.BOOKINGS> getBOOKINGS() {
        if (bookings == null) {
            bookings = new ArrayList<BOOKINGDETAILStype.BOOKINGS>();
        }
        return this.bookings;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="bookingId" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="journeyDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="destination" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="noOfDaysRemain" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BOOKINGS {

        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "bookingId")
        protected Integer bookingId;
        @XmlAttribute(name = "journeyDate")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar journeyDate;
        @XmlAttribute(name = "origin")
        protected String origin;
        @XmlAttribute(name = "destination")
        protected String destination;
        @XmlAttribute(name = "noOfDaysRemain")
        protected Integer noOfDaysRemain;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the bookingId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBookingId() {
            return bookingId;
        }

        /**
         * Sets the value of the bookingId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBookingId(Integer value) {
            this.bookingId = value;
        }

        /**
         * Gets the value of the journeyDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getJourneyDate() {
            return journeyDate;
        }

        /**
         * Sets the value of the journeyDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setJourneyDate(XMLGregorianCalendar value) {
            this.journeyDate = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the destination property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestination() {
            return destination;
        }

        /**
         * Sets the value of the destination property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestination(String value) {
            this.destination = value;
        }

        /**
         * Gets the value of the noOfDaysRemain property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNoOfDaysRemain() {
            return noOfDaysRemain;
        }

        /**
         * Sets the value of the noOfDaysRemain property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNoOfDaysRemain(Integer value) {
            this.noOfDaysRemain = value;
        }

    }

}
